[package]
name = "adventofcode2018"
version = "1.0.0"
authors = ["Dennis Hedegaard <dennis@dhedegaard.dk>"]
edition = "2018"
repository = "https://github.com/dhedegaard/adventofcode2018"

[dependencies]
time = "0.1"
itertools = "0.7"
regex = "1"
prettytable-rs = "0.8"
pathfinding = "1.1.10"
